// Generates landing pages, blog pages, and sitemap.xml from ./content.
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const appDirectory = dirname(dirname(fileURLToPath(import.meta.url)));
const publicDirectory = join(appDirectory, 'public');
const contentDirectory = join(appDirectory, 'content');
const ORIGIN = 'https://tcgcard.fun';

const escapeHtml = (value) =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// Minimal Markdown subset: ## / ### headings, - lists, **bold**, [text](url), paragraphs.
function renderMarkdown(source) {
  const inline = (text) =>
    escapeHtml(text)
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');

  const blocks = source.trim().split(/\n{2,}/);
  return blocks
    .map((block) => {
      const lines = block.split('\n');
      if (lines.every((line) => line.startsWith('- '))) {
        const items = lines.map((line) => `<li>${inline(line.slice(2))}</li>`).join('');
        return `<ul>${items}</ul>`;
      }
      if (block.startsWith('### ')) return `<h3>${inline(block.slice(4))}</h3>`;
      if (block.startsWith('## ')) return `<h2>${inline(block.slice(3))}</h2>`;
      return `<p>${inline(block.replace(/\n/g, ' '))}</p>`;
    })
    .join('\n          ');
}

function parseFrontMatter(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error('Missing front matter');
  const meta = {};
  for (const line of match[1].split('\n')) {
    const separator = line.indexOf(':');
    if (separator === -1) continue;
    meta[line.slice(0, separator).trim()] = line.slice(separator + 1).trim();
  }
  return { meta, body: match[2] };
}

const HEADER = `    <header class="new-header">
      <div class="new-header-inner site-container">
        <a class="new-brand" href="/" aria-label="Card AI home">
          <img src="/assets/card-ai-logo.png" alt="">
          <span>Card AI</span>
        </a>
      </div>
    </header>`;

const FOOTER = `    <footer class="new-footer">
      <div class="new-footer-inner site-container">
        <div class="footer-logo"><img src="/assets/card-ai-logo.png" alt=""><span>Card AI</span></div>
        <div class="new-footer-links" aria-label="Legal and contact">
          <a href="/blog/">Blog</a>
          <a href="/terms">Terms of Service</a>
          <a href="/privacy">Privacy Policy</a>
          <a href="mailto:support@tcgcard.fun">Contact Us</a>
        </div>
      </div>
    </footer>`;

const STORE_ROW = `        <div class="store-buttons" aria-label="Download options">
          <a class="store-badge" href="https://apps.apple.com/us/app/card-ai-tcg-card-scanner/id6793017224" aria-label="Download on the App Store"><img class="store-icon-img" src="/assets/apple-store-icon.png" alt=""><span class="store-text"><small>Download</small><strong>App Store</strong></span></a>
          <span class="store-badge store-badge-disabled" aria-disabled="true"><img class="store-icon-img" src="/assets/google-play-icon.png" alt=""><span class="store-text"><small>Store Link Pending</small><strong>Google Play</strong></span></span>
        </div>`;

const PROOF_ASSETS = {
  scan: {
    src: '/assets/showcase-scan.png',
    alt: 'Card AI scan and candidate review screen',
  },
  prices: {
    src: '/assets/showcase-analysis.png',
    alt: 'Card AI market prices and price history screen',
  },
  portfolio: {
    src: '/assets/showcase-portfolio.png',
    alt: 'Card AI collection value and portfolio screen',
  },
};

function renderShell({
  url,
  title,
  description,
  jsonLd,
  body,
  indexable = true,
  ogType = 'website',
  image = '/assets/hero-phones.png',
}) {
  const blocks = jsonLd
    .map((entry) => `  <script type="application/ld+json">\n${JSON.stringify(entry, null, 2)}\n  </script>`)
    .join('\n');
  return `<!doctype html>
<!-- Generated by scripts/generate-content.mjs. Edit ./content instead. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="${escapeHtml(description)}">
${indexable ? `  <link rel="canonical" href="${ORIGIN}${url}">` : '  <meta name="robots" content="noindex,follow">'}
  <meta property="og:type" content="${escapeHtml(ogType)}">
  <meta property="og:site_name" content="Card AI">
  <meta property="og:title" content="${escapeHtml(title)}">
  <meta property="og:description" content="${escapeHtml(description)}">
${indexable ? `  <meta property="og:url" content="${ORIGIN}${url}">` : ''}
  <meta property="og:image" content="${ORIGIN}${image}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${escapeHtml(title)}">
  <meta name="twitter:description" content="${escapeHtml(description)}">
  <meta name="twitter:image" content="${ORIGIN}${image}">
  <link rel="icon" type="image/png" href="/assets/card-ai-logo.png">
  <link rel="apple-touch-icon" href="/assets/card-ai-logo.png">
${blocks}
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="/site.css">
</head>
<body>
  <div class="marketing-site">
${HEADER}
    <main class="content-main">
${body}
    </main>
${FOOTER}
  </div>
</body>
</html>
`;
}

function renderFaq(faq, heading = 'Questions.') {
  if (!faq?.length) return '';
  const items = faq
    .map(
      ({ q, a }) => `            <details class="faq-item">
              <summary>${escapeHtml(q)}</summary>
              <p>${escapeHtml(a)}</p>
            </details>`,
    )
    .join('\n');
  return `
      <section class="faq-section">
        <div class="faq-layout site-container">
          <h2>${escapeHtml(heading)}</h2>
          <div class="faq-list">
${items}
          </div>
        </div>
      </section>`;
}

function renderProductProof(page) {
  const proof = page.proof;
  const asset = proof && PROOF_ASSETS[proof.kind];
  if (!proof || !asset) throw new Error(`Missing product proof for ${page.slug}`);
  return `      <figure class="product-proof site-container">
        <div class="product-proof-media">
          <img src="${asset.src}" alt="${escapeHtml(`${page.linkLabel}: ${asset.alt}`)}" loading="lazy">
        </div>
        <figcaption>
          <h2>${escapeHtml(proof.title)}</h2>
          <div class="product-proof-copy">
            ${renderMarkdown(proof.body)}
          </div>
          <p class="product-proof-note">Illustrative Card AI screen composite. Values shown are examples; market prices, history, and sold-listing availability depend on the selected card.</p>
        </figcaption>
      </figure>`;
}

function renderLanding(page, all) {
  const ctaLabel = `${page.linkLabel.charAt(0).toLowerCase()}${page.linkLabel.slice(1)}`;
  const sections = page.sections
    .map(
      (section) => `          <section class="content-block">
            <h2>${escapeHtml(section.h2)}</h2>
            ${renderMarkdown(section.body)}
          </section>`,
    )
    .join('\n');

  const related = (page.related ?? [])
    .map((slug) => all.find((candidate) => candidate.slug === slug))
    .filter(Boolean)
    .map((target) => `<li><a href="/${target.slug}">${escapeHtml(target.linkLabel ?? target.h1)}</a></li>`)
    .join('');

  const body = `      <section class="content-hero">
        <div class="site-container">
          <p class="content-eyebrow">${escapeHtml(page.eyebrow)}</p>
          <h1>${escapeHtml(page.h1)}</h1>
          <p class="content-lede">${escapeHtml(page.lede)}</p>
${STORE_ROW}
        </div>
      </section>

${renderProductProof(page)}

      <div class="content-body site-container">
${sections}
${related ? `          <section class="content-block">\n            <h2>Related</h2>\n            <ul class="content-links">${related}</ul>\n          </section>` : ''}
        </div>
${renderFaq(page.faq, `${page.linkLabel ?? page.h1} questions.`)}

      <section class="content-cta">
        <div class="site-container">
          <h2>Try the ${escapeHtml(ctaLabel)} in Card AI.</h2>
          <p>${escapeHtml(page.cta)}</p>
${STORE_ROW}
        </div>
      </section>`;

  const jsonLd = [
    {
      '@context': 'https://schema.org',
      '@type': 'WebPage',
      name: page.title,
      url: `${ORIGIN}/${page.slug}`,
      description: page.description,
      image: `${ORIGIN}${PROOF_ASSETS[page.proof.kind].src}`,
      isPartOf: { '@type': 'WebSite', name: 'Card AI', url: `${ORIGIN}/` },
    },
  ];
  if (page.faq?.length) {
    jsonLd.push({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: page.faq.map(({ q, a }) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: a },
      })),
    });
  }
  return renderShell({ url: `/${page.slug}`, title: page.title, description: page.description, jsonLd, body });
}

function renderPost(post) {
  const figure = post.meta.image
    ? `          <figure class="content-figure">
            <img src="${escapeHtml(post.meta.image)}" alt="${escapeHtml(post.meta.imageAlt)}">
            <figcaption>${escapeHtml(post.meta.imageCaption)}</figcaption>
          </figure>`
    : '';
  const body = `      <article class="content-article">
        <div class="site-container">
          <p class="content-eyebrow"><a href="/blog/">Blog</a></p>
          <h1>${escapeHtml(post.meta.h1)}</h1>
          <p class="content-meta"><time datetime="${post.meta.date}">${post.meta.date}</time></p>
${figure}
          <div class="content-prose">
          ${renderMarkdown(post.body)}
          </div>
        </div>
      </article>`;

  const jsonLd = [
    {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: post.meta.h1,
      description: post.meta.description,
      image: `${ORIGIN}${post.meta.image}`,
      datePublished: post.meta.date,
      dateModified: post.meta.date,
      mainEntityOfPage: `${ORIGIN}/blog/${post.slug}`,
      author: { '@type': 'Organization', name: 'Card AI', url: `${ORIGIN}/` },
      publisher: {
        '@type': 'Organization',
        name: 'Card AI',
        logo: { '@type': 'ImageObject', url: `${ORIGIN}/assets/card-ai-logo.png` },
      },
    },
    {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: `${ORIGIN}/` },
        { '@type': 'ListItem', position: 2, name: 'Blog', item: `${ORIGIN}/blog/` },
        { '@type': 'ListItem', position: 3, name: post.meta.h1 },
      ],
    },
  ];
  return renderShell({
    url: `/blog/${post.slug}`,
    title: post.meta.title,
    description: post.meta.description,
    jsonLd,
    body,
    ogType: 'article',
    image: post.meta.image,
  });
}

function renderBlogIndex(posts) {
  const items = posts
    .map(
      (post) => `            <li class="blog-card">
              <a href="/blog/${post.slug}"><img class="blog-card-image" src="${escapeHtml(post.meta.image)}" alt="${escapeHtml(post.meta.imageAlt)}"><h2>${escapeHtml(post.meta.h1)}</h2></a>
              <p>${escapeHtml(post.meta.description)}</p>
              <time datetime="${post.meta.date}">${post.meta.date}</time>
            </li>`,
    )
    .join('\n');

  const body = `      <section class="content-hero">
        <div class="site-container">
          <p class="content-eyebrow">Card AI Blog</p>
          <h1>Trading card values, scanning, and collecting.</h1>
          <p class="content-lede">Guides on what your cards are worth, how card prices move, and how to keep a collection organized.</p>
        </div>
      </section>

      <div class="content-body site-container">
        <ul class="blog-list">
${items}
        </ul>
      </div>`;

  return renderShell({
    url: '/blog/',
    title: 'Card AI Blog: Trading Card Values & Collecting Guides',
    description:
      'Guides on checking trading card values, understanding card price trends, grading, and keeping a collection organized.',
    jsonLd: [
      {
        '@context': 'https://schema.org',
        '@type': 'Blog',
        name: 'Card AI Blog',
        url: `${ORIGIN}/blog/`,
        blogPost: posts.map((post) => ({
          '@type': 'BlogPosting',
          headline: post.meta.h1,
          url: `${ORIGIN}/blog/${post.slug}`,
          datePublished: post.meta.date,
        })),
      },
    ],
    body,
  });
}

function render404(landing) {
  const links = landing
    .slice(0, 6)
    .map((page) => `<li><a href="/${page.slug}">${escapeHtml(page.linkLabel ?? page.h1)}</a></li>`)
    .join('');
  const body = `      <section class="content-hero">
        <div class="site-container">
          <p class="content-eyebrow">404</p>
          <h1>That page does not exist.</h1>
          <p class="content-lede">The link may be out of date. Here is where to go instead.</p>
          <ul class="content-links" style="margin-top:32px">
            <li><a href="/">Card AI home</a></li>
            <li><a href="/blog/">Blog</a></li>
${links ? `            ${links}` : ''}
          </ul>
        </div>
      </section>`;
  return renderShell({
    url: '/404',
    title: 'Page not found | Card AI',
    description: 'The page you were looking for does not exist.',
    jsonLd: [],
    body,
    indexable: false,
  });
}

const GROUPS = [
  { title: 'Trading card games', match: (p) => p.group === 'tcg' },
  { title: 'Sports cards', match: (p) => p.group === 'sports' },
  { title: 'By feature', match: (p) => p.group === 'feature' },
];

function renderBrowseBlock(landing, posts) {
  const columns = GROUPS.map((group) => {
    const items = landing
      .filter(group.match)
      .map((page) => `<li><a href="/${page.slug}">${escapeHtml(page.linkLabel ?? page.h1)}</a></li>`)
      .join('');
    return items ? `            <div class="browse-col">\n              <h3>${group.title}</h3>\n              <ul class="content-links">${items}</ul>\n            </div>` : '';
  }).filter(Boolean);

  const guides = posts
    .map((post) => `<li><a href="/blog/${post.slug}">${escapeHtml(post.meta.h1)}</a></li>`)
    .join('');
  columns.push(`            <div class="browse-col">\n              <h3>Guides</h3>\n              <ul class="content-links">${guides}<li><a href="/blog/">All guides</a></li></ul>\n            </div>`);

  return `      <section class="browse-section" id="browse">
        <div class="site-container">
          <h2>Browse by game and feature.</h2>
          <div class="browse-grid">
${columns.join('\n')}
          </div>
        </div>
      </section>`;
}

function renderSitemap(urls) {
  const entries = urls
    .map(
      ({ loc, priority }) => `  <url>
    <loc>${ORIGIN}${loc}</loc>
    <priority>${priority}</priority>
  </url>`,
    )
    .join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by scripts/generate-content.mjs. -->\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</urlset>\n`;
}

// ---- build ----
const landingFiles = (await readdir(join(contentDirectory, 'landing'))).filter((f) => f.endsWith('.mjs')).sort();
const landing = [];
for (const file of landingFiles) {
  const module = await import(new URL(`../content/landing/${file}`, import.meta.url));
  landing.push(module.default);
}

const blogFiles = (await readdir(join(contentDirectory, 'blog'))).filter((f) => f.endsWith('.md')).sort();
const posts = [];
for (const file of blogFiles) {
  const raw = await readFile(join(contentDirectory, 'blog', file), 'utf8');
  const { meta, body } = parseFrontMatter(raw);
  posts.push({ slug: file.replace(/\.md$/, ''), meta, body });
}
posts.sort((a, b) => b.meta.date.localeCompare(a.meta.date));

for (const page of landing) {
  await writeFile(join(publicDirectory, `${page.slug}.html`), renderLanding(page, landing), 'utf8');
}

await mkdir(join(publicDirectory, 'blog'), { recursive: true });
for (const post of posts) {
  await writeFile(join(publicDirectory, 'blog', `${post.slug}.html`), renderPost(post), 'utf8');
}
await writeFile(join(publicDirectory, 'blog', 'index.html'), renderBlogIndex(posts), 'utf8');

await writeFile(join(publicDirectory, '404.html'), render404(landing), 'utf8');

await writeFile(
  join(publicDirectory, 'sitemap.xml'),
  renderSitemap([
    { loc: '/', priority: '1.0' },
    ...landing.map((page) => ({ loc: `/${page.slug}`, priority: '0.8' })),
    { loc: '/blog/', priority: '0.6' },
    ...posts.map((post) => ({ loc: `/blog/${post.slug}`, priority: '0.5' })),
    { loc: '/privacy', priority: '0.3' },
    { loc: '/terms', priority: '0.3' },
  ]),
  'utf8',
);

console.log(`generated ${landing.length} landing pages, ${posts.length} blog posts, sitemap`);

// index.html 的链接块与 llms.txt 的页面清单由标记区间维护
const indexPath = join(publicDirectory, 'index.html');
let indexHtml = await readFile(indexPath, 'utf8');
indexHtml = indexHtml.replace(
  /<!-- BEGIN generated-links -->[\s\S]*?<!-- END generated-links -->/,
  `<!-- BEGIN generated-links -->\n${renderBrowseBlock(landing, posts)}\n      <!-- END generated-links -->`,
);
await writeFile(indexPath, indexHtml, 'utf8');

const llmsPath = join(publicDirectory, 'llms.txt');
let llms = await readFile(llmsPath, 'utf8');
const llmsList = [
  ...landing.map((page) => `- [${page.linkLabel ?? page.h1}](${ORIGIN}/${page.slug}): ${page.description}`),
  `- [Blog](${ORIGIN}/blog/): Guides on card values, grading, and collection tracking.`,
  ...posts.map((post) => `- [${post.meta.h1}](${ORIGIN}/blog/${post.slug}): ${post.meta.description}`),
].join('\n');
llms = llms.replace(
  /(## Pages\n\n)[\s\S]*?(\n\n## )/,
  `$1${llmsList}$2`,
);
await writeFile(llmsPath, llms, 'utf8');

console.log('index links + llms.txt updated');
